package MyBB::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MyBB::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:mydb',
        user => 'root',
        password => 'loveforever',
    }
);

=head1 NAME

MyBB::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MyBB>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MyBB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
